#:schema node_modules/wrangler/config-schema.json
name = "sanrio-vfes-events"
compatibility_date = "2024-11-06"
main = "./worker.ts"
assets = { directory = "./build/client" }

[vars]
MY_VAR = "My Value"
GOOGLE_ANALYTICS_ID = "G-P4KGN8TR8C"
